### Generated by rprotoc. DO NOT EDIT!
### <proto file: ip_event.proto>
# package lookout.backend_coding_questions.q1;
# 
# message IpEvent {
#   // A unique SHA256 hash of an app, used as a unique ID for the app
#   required string app_sha256 = 1;
#   // A single IPV4 address that an app has connected to.
#   required int64 ip = 2;
# }
require 'protobuf/message/message'
require 'protobuf/message/enum'
require 'protobuf/message/service'
require 'protobuf/message/extend'

module Lookout
  module BackendCodingQuestions
    module Q1
      class IpEvent < ::Protobuf::Message
        defined_in __FILE__
        required :string, :app_sha256, 1
        required :int64, :ip, 2
      end
    end
  end
end